name: ci

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.8.0
    - name: produce version info file
      run: 'echo {\"version\": \"${{ github.sha }}\"} > src/assets/version.json'
    - name: npm install, build, and test
      env:
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        external_repository: aria-music/aria-music.github.io
        publish_dir: dist
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_RELEASE }}
