name: Test and deploy to Github pages

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/cache@v1.0.3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@mnsinri'
    - name: produce version info file
      run: 'echo {\"version\": \"${{ github.sha }}\"} > src/assets/version.json'
    - name: npm install, build, and test
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run build --if-present
    - name: deploy to github pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_SECRET }}
        EXTERNAL_REPOSITORY: aria-music/aria-music.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
    - name: notify to discord
      uses: sarisia/actions-status-discord
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        job: build aria-web
